### PR TITLE
Added support for ESP8266.

### PR DESCRIPTION
**Pull request by slaff**

### CODE REVIEW

**Comment by NicoHood** [comment]
The patch looks fine, thanks for submitting! I did not test the code, but unless it does not break anything (it looks good to me) I am willing to merge it.

Could you please fix the whitespace problems? It looks like some lines are either indented wrong or you mixed tabs and spaces. Please use 4 spaces for indention. I am happy to merge it then :)

**Comment by slaff** [comment]
> Could you please fix the whitespace problems?

Should be better now. And I hope I can test the promised performance on ESP8266 in real-life scenarios :)

**Comment by slaff** [comment]
@NicoHood Should be better now.

**Comment by NicoHood** [comment]
This looks way better now. I cannot test if it works, but it should not break anything. If you fix the last indention errors I am going to merge this. Thanks a lot! :)

If someone else could verify that this is working properly, that'd be nice.

**Comment by slaff** [comment]
We are evaluating the library to use it in Sming (https://github.com/slaff/Sming/tree/feature/IRL-remote). The indentation changes are done.

**Comment by NicoHood** [comment]
I merged the PR. I've fixed DMBS myself, awaiting this PR to get merged as well:
https://github.com/abcminiuser/dmbs/pull/32

For you everything should work now. Do you wish a new library tag?

**Comment by NicoHood** [comment]
Tagged as release 2.0.2
https://github.com/NicoHood/IRLremote/releases/tag/2.0.2

**Pull request merged**
